imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

oro_file_inventor:
    root_search_folders:
        - /Users/zeykzso/Sites/file-matcher/src/Oro/FileInventorBundle/Tests/ExampleFileRepository
        - /Users/zeykzso/Sites/file-matcher/src/Oro/FileInventorBundle/Tests/ExampleFileRepository2
